/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MonitoringImport } from './routes/monitoring'
import { Route as AlertingImport } from './routes/alerting'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MonitoringRoute = MonitoringImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRoute,
} as any)

const AlertingRoute = AlertingImport.update({
  id: '/alerting',
  path: '/alerting',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/alerting': {
      id: '/alerting'
      path: '/alerting'
      fullPath: '/alerting'
      preLoaderRoute: typeof AlertingImport
      parentRoute: typeof rootRoute
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerting': typeof AlertingRoute
  '/monitoring': typeof MonitoringRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerting': typeof AlertingRoute
  '/monitoring': typeof MonitoringRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/alerting': typeof AlertingRoute
  '/monitoring': typeof MonitoringRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alerting' | '/monitoring'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alerting' | '/monitoring'
  id: '__root__' | '/' | '/alerting' | '/monitoring'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertingRoute: typeof AlertingRoute
  MonitoringRoute: typeof MonitoringRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertingRoute: AlertingRoute,
  MonitoringRoute: MonitoringRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/alerting",
        "/monitoring"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/alerting": {
      "filePath": "alerting.jsx"
    },
    "/monitoring": {
      "filePath": "monitoring.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
