/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AlertingImport } from './routes/alerting'

// Create/Update Routes

const AlertingRoute = AlertingImport.update({
  id: '/alerting',
  path: '/alerting',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/alerting': {
      id: '/alerting'
      path: '/alerting'
      fullPath: '/alerting'
      preLoaderRoute: typeof AlertingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/alerting': typeof AlertingRoute
}

export interface FileRoutesByTo {
  '/alerting': typeof AlertingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/alerting': typeof AlertingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/alerting'
  fileRoutesByTo: FileRoutesByTo
  to: '/alerting'
  id: '__root__' | '/alerting'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AlertingRoute: typeof AlertingRoute
}

const rootRouteChildren: RootRouteChildren = {
  AlertingRoute: AlertingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/alerting"
      ]
    },
    "/alerting": {
      "filePath": "alerting.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
